# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreTextTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'DTCoreText'
     pod 'SnapKit', '~> 3.1.2'



  # Pods for CoreTextTest

  target 'CoreTextTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoreTextTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
